name: Deploy Admin Worker (Cloudflare)

on:
  push:
    branches: [main]
    paths:
      - "apps/admin/**"
      - ".github/workflows/cf-admin.yml"

jobs:
  deploy-admin:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Inject CI variables into wrangler.toml
        run: |
          sed -i "s/__PROD_DOMAIN__/${PROD_DOMAIN}/" apps/admin/wrangler.toml
          sed -i "s/__TEST_DOMAIN__/${TEST_DOMAIN}/" apps/admin/wrangler.toml

      - name: Deploy to Cloudflare Workers (production)
        run: bunx wrangler deploy --config apps/admin/wrangler.toml --env production
