name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'apps/docs-site/**'
      - 'docs/**'
      - 'packages/shared-ts/**'
      - 'packages/dto/**'
      - 'packages/trpc/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - 'tsconfig.base.json'
  pull_request:
    paths:
      - 'apps/docs-site/**'
      - 'docs/**'
      - 'packages/shared-ts/**'
      - 'packages/dto/**'
      - 'packages/trpc/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - 'tsconfig.base.json'

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.8.0
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      # - run: pnpm exec nx run-many -t lint test build typecheck
      - run: pnpm exec nx fix-ci
        if: always()

  docs-site:
    needs: main
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.18.3
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Build docs-site
        run: pnpm exec nx run docs-site:build

      - name: Setup Pages
        if: success()
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: success()
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/apps/docs-site'

      - name: Deploy to GitHub Pages
        if: success()
        id: deployment
        uses: actions/deploy-pages@v4
